ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(50),
ADD COLUMN IF NOT EXISTS shipping_address TEXT,
ADD COLUMN IF NOT EXISTS note TEXT,
ADD COLUMN IF NOT EXISTS subtotal DECIMAL(19, 2),
ADD COLUMN IF NOT EXISTS shipping_fee DECIMAL(19, 2),
ADD COLUMN IF NOT EXISTS order_code VARCHAR(255);
