ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS address_id BIGINT,
ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(19, 2),
ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50),
ADD COLUMN IF NOT EXISTS user_id BIGINT;
